apiVersion: v1
kind: Service
metadata:
  name: micro-sender
spec:
  selector:
    app: micro-sender
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-sender
  template:
    metadata:
      labels:
        app: micro-sender
    spec:
      containers:
        - name: micro-sender
          image: valashchukd/micro-sender:v2
          ports:
            - containerPort: 8081
