apiVersion: v1
kind: Service
metadata:
  name: micro-collector
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: micro-collector
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: micro-collector
  template:
    metadata:
      labels:
        app: micro-collector
    spec:
      containers:
        - name: micro-collector
          image: valashchukd/micro-collector:v6
          ports:
            - containerPort: 8082