apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - name: "prometheus"
    port: 9090
    protocol: "TCP"
    targetPort: 9090
  selector:
    app: prometheus
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations: {}
  labels:
    app: "prometheus"
  name: "prometheus"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "prometheus"
  template:
    metadata:
      annotations: {}
      labels:
        app: "prometheus"
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.44.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus-config        