scrape_configs:
  - job_name: 'MicroCollector'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['micro-sender:8081', 'micro-collector:8082', 'micro-recipient:8083', 'micro-visualizer:8084']
        labels:
          application: 'MicroCollector'